# Generated by Django 2.0.6 on 2020-04-10 20:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promocode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=20)),
                ('action', models.CharField(default='', max_length=100)),
                ('count', models.BigIntegerField(default=0)),
                ('used', models.BigIntegerField(default=0)),
                ('description', models.CharField(default='', max_length=4000)),
                ('create_date', models.DateTimeField(default=datetime.datetime.now)),
                ('end_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
