# Generated by Django 2.0.6 on 2020-04-10 20:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=datetime.datetime.now)),
                ('level', models.CharField(choices=[('I', 'INFO'), ('E', 'ERROR'), ('W', 'WARN'), ('D', 'DEBUG')], default='US', max_length=1)),
                ('description', models.CharField(default='', max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name='OnlineStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
