# Generated by Django 3.0 on 2019-12-22 18:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0005_freezeprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('solution', models.CharField(max_length=4000)),
                ('create_date', models.DateTimeField(default=datetime.datetime.now)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profile.Profile')),
            ],
        ),
    ]
