# Generated by Django 2.0.6 on 2020-04-10 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0007_auto_20200409_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='userType',
            field=models.CharField(choices=[('AD', 'Admin'), ('TS', 'Tester'), ('US', 'User'), ('MD', 'Moderator'), ('HP', 'Helper')], default='US', max_length=2),
        ),
    ]
