# Generated by Django 2.0.6 on 2020-04-12 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0011_auto_20200412_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='DevLogsAccess',
            field=models.BooleanField(default=False),
        ),
    ]
