# Generated by Django 2.0.6 on 2020-04-13 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0015_auto_20200413_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.CharField(default='/image/default.png', max_length=100),
        ),
    ]
