# Generated by Django 2.0.6 on 2020-04-14 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0017_auto_20200413_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='FriendsAccess',
            field=models.BooleanField(default=True),
        ),
    ]
