# Generated by Django 2.0.6 on 2020-04-14 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0018_permission_friendsaccess'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='online',
        ),
        migrations.AddField(
            model_name='permission',
            name='WallAccess',
            field=models.BooleanField(default=True),
        ),
    ]
