# Generated by Django 2.0.6 on 2020-04-14 12:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0019_auto_20200414_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='online',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
