# Generated by Django 3.0 on 2019-12-22 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0004_auto_20191222_2132'),
        ('Wall', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('type_doc', models.CharField(choices=[('PC', 'Picture'), ('DC', 'Document')], default='PC', max_length=2)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='photo/')),
                ('access_key', models.CharField(max_length=18)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.CharField(default='', max_length=4000),
        ),
        migrations.CreateModel(
            name='WallLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profile.Profile')),
                ('wall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Wall.Post')),
            ],
        ),
    ]
