# Generated by Django 2.0.6 on 2020-04-13 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wall', '0003_auto_20200409_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_posts', to='Profile.Profile'),
        ),
        migrations.AlterField(
            model_name='post',
            name='original',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
