# Generated by Django 3.0 on 2019-12-21 18:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_auto_20191221_2103'),
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthCodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=16)),
                ('confirm', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ConfirmCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=7)),
                ('authInfoProfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auth.AuthInfoProfile')),
            ],
        ),
        migrations.CreateModel(
            name='restorationApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(default=datetime.datetime.now)),
                ('end_date', models.DateTimeField(default=datetime.datetime.now)),
                ('solution', models.TextField()),
                ('status', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profile.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='accesstoken',
            name='perms',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Profile.Permission'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accesstoken',
            name='access_token',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='api_info',
            name='name',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='api_info',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AlterField(
            model_name='authapp',
            name='perms',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profile.Permission'),
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
    ]
