# Generated by Django 3.0 on 2019-12-21 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0002_auto_20191221_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authinfoprofile',
            name='password',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='restorationapplication',
            name='solution',
            field=models.TextField(default=''),
        ),
    ]
