# Generated by Django 3.0 on 2019-12-22 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0004_auto_20191222_2139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authapp',
            old_name='date',
            new_name='create_date',
        ),
    ]
