# Generated by Django 3.0 on 2019-12-22 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0005_auto_20191222_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='authapp',
            name='name',
            field=models.CharField(default='Unnamed app', max_length=40),
        ),
    ]
