# Generated by Django 3.0 on 2019-12-22 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0006_authapp_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AuthCodes',
            new_name='AuthCode',
        ),
    ]
