# Generated by Django 3.0.5 on 2020-04-09 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0007_auto_20191222_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesstoken',
            name='worked',
            field=models.BooleanField(default=True),
        ),
    ]
