# Generated by Django 2.0.6 on 2020-04-10 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0008_accesstoken_worked'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthCode',
        ),
    ]
