# Generated by Django 2.0.6 on 2020-04-12 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0009_delete_authcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='authinfoprofile',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='confirmcode',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
