from django.contrib import admin
from .models import *

admin.site.register(Profile)
admin.site.register(App)
admin.site.register(AuthLoginInfo)
admin.site.register(AuthInfo)
admin.site.register(Wall)
admin.site.register(Widjets)
admin.site.register(historyActivity)
admin.site.register(Subscription)
admin.site.register(Subscriber)
admin.site.register(Comments)
admin.site.register(Attachments)
admin.site.register(Permissions)
admin.site.register(Errors)
admin.site.register(Photo)
admin.site.register(Link)
admin.site.register(Message)
admin.site.register(Dialog)
admin.site.register(Email)
admin.site.register(Payment)
admin.site.register(PayHistory)
admin.site.register(Check)
admin.site.register(CloneProfile)
admin.site.register(Bot)
admin.site.register(ExpHistory)
admin.site.register(Experience)
admin.site.register(Notification)
admin.site.register(Product)
admin.site.register(Debug)
admin.site.register(SystemParams)
